package com.bank.bian.casemanagementfinancialcrime;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Case Management Financial Crime
 *
 * Business Area:      Risk and Compliance
 * Business Domain:    Financial Crime
 * Functional Pattern: Manage
 * Asset Type:         Financial Crime Case
 * Control Record:     Financial Crime Case Management Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Case Management Financial Crime — BIAN Semantic API")
                .description("Service Domain 'Case Management Financial Crime' (Manage pattern) "
                        + "operating on the 'Financial Crime Case Management Plan' control record.")
                .version("0.1.0"));
    }
}
